version: "3.3"
services:
  web:
    image: boselane6633/express-api-app:latest
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    env_file:
      - environment/docker_web.env
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  mqlight:
    image: ibmcom/mqlight
    environment:
      - LICENSE=accept
    ports:
      - "5672:5672"
      - "9180:9180"
    volumes:
    - ${DKR_MQLIGHT_DIR}:/var/mqlight
