---
apiVersion: v1
kind: Namespace
metadata:
  name: express
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: express
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: express
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: express
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mqlight
  namespace: express
spec:
  selector:
    app: mqlight
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 9180
      targetPort: 9180
      name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqlight
  namespace: express
spec:
  selector:
    matchLabels:
      app: mqlight
  template:
    metadata:
      labels:
        app: mqlight
    spec:
      containers:
        - name: mqlight
          image: ibmcom/mqlight
          ports:
            - containerPort: 5672
            - containerPort: 9180
          env:
            - name: LICENSE
              value: accept
---
apiVersion: v1
kind: Service
metadata:
  name: express-api
  namespace: express
spec:
  selector:
    app: express-api
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  namespace: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: boselane6633/express-api-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: EXP_API_ENV_DEPLOYMENT
              value: "K8S"
            - name: EXP_API_APP_DIR
              value: "/usr/src/app"
            - name:  EXP_API_PORT
              value: "3000"
            - name: EXP_API_MONGO_URI
              value: "mongodb://mongo:27017/"
            - name: EXP_API_AMQP_URI
              value: "amqp://mqlight:5672"
            - name: EXP_API_MONGO_DB_NAME
              value: "EXPRESS_API"
            - name: EXP_API_LOGGING_LEVEL
              value: "info"
            - name: EXP_API_NODE_ENV_PRODUCTION
              value: "yes"
            - name: EXP_API_HTTPS
              value: "no"
            - name: EXP_API_APP_IP
              value: 127.0.0.1
            - name: EXP_API_INDEX_ROUTE
              value: "/"
            - name: EXP_API_API_ROUTE
              value: "/api"
            - name: EXP_API_USER_ROUTE
              value: "/users"
            - name: EXP_API_API_VERSION
              value: "1.1.0"
            - name: EXP_API_CERT_PROVIDER
              value: "SELF_SIGNED"
            - name: EXP_API_KEY_STORE
              value: "/bin/keystore/"
            - name: "EXP_API_APP_CERT"
              value: "cert.pem"
            - name: EXP_API_APP_KEY
              value: "key.pem"
            - name:   EXP_API_APP_EXTERNAL_ERROR
              value: "false"

          imagePullPolicy: Always